version: '3'

services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    build: .
    volumes:
      - ./:/app
    command: 'yarn start'
    ports:
      - 9090:9090

